name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  base_path:
    description: 'Path to base size file'
    required: true
  pr_path:
    description: 'Path to PR size file'
    required: true
outputs:
  base_size:
    description: 'Base bundle size'
  pr_size:
    description: 'PR bundle size'
  diff:
    description: 'Difference'
  percentDifference:
    description: '% difference'
runs:
  using: 'node12'
  main: 'index.js'
